backend:
  name: github
  repo: chesteralan/Creative-NuxtJs
site_url: https://creative-nuxtjs.netlify.app/
display_url: https://creative-nuxtjs.netlify.app/
local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: false

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'content/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - { label: 'Global description', name: 'site_description', widget: 'string' }
          - { label: 'Default Page Slug', name: 'default_page', widget: 'string', default: 'homepage' }
  
